[package]
name = "rpmdb"
version = "0.1.0"
edition = "2021"
authors = [
    "yybit <yybit2@gmail.com>",
]
license = "MIT"
homepage = "https://github.com/yybit/rpmdb-rs"
repository = "https://github.com/yybit/rpmdb-rs"
documentation = "https://docs.rs/rpmdb"
description = "Rust implementation of rpmdb"
readme = "README.md"
keywords = ["rpm", "rpmdb", "database"]
categories = ["database", "parser-implementations"]
include = [
    "src/**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode_reloaded = { version = "3.1", features = ["serde"] }
byteorder = "1.5.0"
serde = { version = "1.0", features = ["derive"] }

anyhow = "1.0.75"
thiserror = "1.0.50"

rusqlite = "0.37.0"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27.1", default-features = false, features = ["fs"] }
